export const SERVICES = {
  API_GATEWAY: 'API_GATEWAY',
  AUTH_SERVICE: 'AUTH_SERVICE',
  USERS_SERVICE: 'USERS_SERVICE',
  EVENTS_SERVICE: 'EVENTS_SERVICE',
  TICKETS_SERVICE: 'TICKETS_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  PAYMENT_SERVICE: 'PAYMENT_SERVICE',
} as const;

export const SERVICES_PORTS = {
  API_GATEWAY: 3000,
  AUTH_SERVICE: 3001,
  USERS_SERVICE: 3002,
  EVENTS_SERVICE: 3003,
  TICKETS_SERVICE: 3004,
  NOTIFICATION_SERVICE: 3005,
  PAYMENT_SERVICE: 3006,
} as const;
